### ISSUE TITLE
paired-end merging optional

### ISSUE THREAD

**Issue by andreott** [fischer-hub/metagenomics#34]
The authors of humann/metaphlan opt rather against merging paired-end reads. So we should rather make it also just optional.

https://forum.biobakery.org/t/paired-end-files-humann2/396

**Comment by fischer-hub** [comment]
This is actually already implemented (I just have to add it to the documentation still ..) with setting the `merger=` flag to `none`.
So with `merger=none` set, the pipeline will just concatenate both read files (when run in paired mode).
Maybe this is not the most intuitive solution.
