### ISSUE TITLE
trimmomatic trap

### ISSUE THREAD

**Issue by andreott** [fischer-hub/metagenomics#35]
When Trimmomatic will detect fully overlapping read pairs, it will keep only one of them and the other will be removed. This leads reads in one trimmed fq file with missing pair in the other and can cause issues for some downstream tools.

https://github.com/fischer-hub/metagenomics/blob/76df92fbe58122c6f0cd345356a25bfb1f579715/rules/trimmomatic.smk#L18

Can be prevented by adding a ':True' at the end
`trimmer=[f"ILLUMINACLIP:{ADPT_PE}:{MAX_MISMATCH}:{P_TH}:{S_TH}:True"]`

**Comment by fischer-hub** [comment]
Thanks for the hint! I think this happened to me once and I was already wondering why I couldn't merge the reads anymore!
